{% set name = "paramspace" %}
{% set version = "2.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d96d93f8af734b334548d3edf16bde335d4f4d9fd5e67a3c88955fd7772db242

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.17.3
    - ruamel.yaml >=0.16.5
    - xarray >=0.10.9

test:
  imports:
    - paramspace
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://gitlab.com/blsqr/paramspace
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE

  summary: Dictionary-based, multi-dimensional parameter space iteration
  description: |
    paramspace is a python package that makes it easy to iterate over a
    multidimensional parameter space, where each point corresponds to a
    dict-like object. It integrates tightly with YAML to make definition of
    parameter spaces and sweeps super simple.
  doc_url: https://paramspace.readthedocs.io/en/latest/
  dev_url: https://gitlab.com/blsqr/paramspace

extra:
  recipe-maintainers:
    - blsqr
